using SimpleMigrations;

namespace Uow.EntityFramework.Migrator.Migrations;

[Migration(1, "CreateEntityTable")]
public class Migration001_CreateEntityTable : Migration
{
    /*
     * Generated by using `dotnet ef` to generate SQL from Uow.EntityFrameworkExample
     * Up: `dotnet ef migrations script 0 CreateEntityTable`
     * Down: `dotnet ef migrations script CreateEntityTable 0`
     */

    protected override void Up()
    {
        Execute(@"
IF OBJECT_ID(N'[__EFMigrationsHistory]') IS NULL
BEGIN
    CREATE TABLE [__EFMigrationsHistory] (
        [MigrationId] nvarchar(150) NOT NULL,
        [ProductVersion] nvarchar(32) NOT NULL,
        CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY ([MigrationId])
    );
END;

BEGIN TRANSACTION;

CREATE TABLE [Entities] (
    [Id] int NOT NULL IDENTITY,
    [Value] int NOT NULL,
    CONSTRAINT [PK_Entities] PRIMARY KEY ([Id])
);

INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
VALUES (N'20230305213656_CreateEntityTable', N'7.0.3');

COMMIT;
");
    }

    protected override void Down()
    {
        Execute(@"
BEGIN TRANSACTION;

DROP TABLE [Entities];

DELETE FROM [__EFMigrationsHistory]
WHERE [MigrationId] = N'20230305213656_CreateEntityTable';

COMMIT;
");
    }
}
